lvi_sam:

  point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"

  # Lidar Params
  use_lidar: 1                          # whether use depth info from lidar or not
  lidar_skip: 0                         # skip this amount of scans
  align_camera_lidar_estimation: 1   # align camera and lidar estimation for visualization
        
  cams: ["cam0", "cam1"]

  #imu parameters       The more accurate parameters you provide, the worse performance
  imu:
    topic: "/imu_raw"
    acc_n: 0.02         # accelerometer measurement noise standard deviation.
    gyr_n: 0.01         # gyroscope measurement noise standard deviation.
    acc_w: 0.002        # accelerometer bias random work noise standard deviation.
    gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.
    g_norm: 9.805       #

  # Feature tracker parameters
  max_cnt: 150            # max feature number in feature tracking
  min_dist: 10            # min distance between two features 
  freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
  F_threshold: 1.0        # ransac threshold (pixel)
  show_track: 1        # publish tracking image as topic
  equalize: 1          # if image is too dark or light, trun on equalize to find enough features

  # Optimization parameters
  max_solver_time: 0.035   # max solver itration time (ms), to guarantee real time
  max_num_iterations: 10   # max solver itrations, to guarantee real time
  keyframe_parallax: 10.0  # keyframe selection threshold (pixel)

  # Unsynchronization parameters
  estimate_td: 1         # online estimate time offset between camera and imu
  td: 0                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

  # Rolling shutter parameters

  # Loop closure parameters
  loop_closure: 1                    # start loop closure
  skip_time: 0.0
  skip_dist: 0.0
  debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
  match_image_scale: 0.5
  vocabulary_file: "/config/brief_k10L6.bin"
  brief_pattern_file: "/config/brief_pattern.yml"
